# Generated by Django 5.2.12 on 2026-03-12 15:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workflow_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('blocked', 'Blocked'), ('completed', 'Completed'), ('failed', 'Failed'), ('timed_out', 'Timed Out')], default='pending', max_length=20)),
                ('total_tokens', models.IntegerField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('wall_clock_seconds', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('error_details', models.JSONField(blank=True, default=dict)),
                ('conflict_log', models.JSONField(blank=True, default=list)),
                ('triggered_by', models.CharField(max_length=100)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('langfuse_trace_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_runs', to='core.agency')),
                ('end_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_runs', to='core.endclient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowPhaseOutput',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phase_id', models.CharField(max_length=100)),
                ('output_type', models.CharField(max_length=100)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('summary', models.TextField(blank=True, default='')),
                ('artifact_type', models.CharField(blank=True, default='', max_length=50)),
                ('structured_data', models.JSONField(blank=True, default=dict)),
                ('html_content', models.TextField(blank=True, default='')),
                ('markdown_source', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workflow_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_outputs', to='orchestrator.workflowrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_id', models.CharField(max_length=255)),
                ('agent_type', models.CharField(max_length=100)),
                ('phase_id', models.CharField(max_length=100)),
                ('total_tokens', models.IntegerField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workflow_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='orchestrator.workflowrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowToolCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_name', models.CharField(max_length=255)),
                ('call_count', models.IntegerField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('avg_latency_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workflow_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='orchestrator.workflowrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
