# Generated by Django 5.2.12 on 2026-03-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0004_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('waiting_for_input', 'Waiting For Input'), ('completed', 'Completed'), ('failed', 'Failed'), ('timed_out', 'Timed Out')], default='pending', max_length=20),
        ),
    ]
