# Generated by Django 5.2.12 on 2026-03-12 15:10

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedCopy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('copy_type', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_copies', to='marketing.campaign')),
                ('end_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_copies', to='core.endclient')),
            ],
            options={
                'verbose_name_plural': 'approved copies',
            },
        ),
        migrations.CreateModel(
            name='BrandVoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('end_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_voices', to='core.endclient')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('end_client', 'is_active'), name='unique_active_brand_voice_per_client')],
            },
        ),
    ]
