# Generated by Django 5.2.12 on 2026-03-12 15:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audit_type', models.CharField(max_length=100)),
                ('findings', models.JSONField(blank=True, default=dict)),
                ('score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('end_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='core.endclient')),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('campaign_type', models.CharField(max_length=100)),
                ('status', models.CharField(default='draft', max_length=50)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('end_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='core.endclient')),
            ],
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision_type', models.CharField(max_length=100)),
                ('rationale', models.TextField()),
                ('outcome', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='marketing.campaign')),
                ('end_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='core.endclient')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('term', models.CharField(max_length=500)),
                ('search_volume', models.IntegerField(blank=True, null=True)),
                ('difficulty', models.FloatField(blank=True, null=True)),
                ('intent', models.CharField(max_length=50)),
                ('status', models.CharField(default='discovered', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('end_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='core.endclient')),
            ],
        ),
    ]
